#include<emscripten.h>
#include"../d.h"
#include"../devents.h"
#include"../dplatform.h"

/* This is the drws-lib "driver" for emscripten.
 *
 * You can use a command like
 *  "emcc yourCode.c -o yourOutput.js -sASYNCIFY"
 *  to compile your code. This should create two
 *  files, "yourOutput.js" and "yourOutput.wasm".
 *  In html, you can run the wasm with a script
 *  tag like
 *  '<script src="yourOutput.js"></script>'. Make
 *  sure that in the page there is a canvas tag
 *  with an id of "drws-lib-canvas" like '<canvas
 *  id="drws-lib-canvas"></canvas>'.
 *
 * The script tag that runs the JS (generated by
 *  emscripten) should automatically run main().
 */

/* 50 key events can happen each frame. */
#define D_D_KEYEVENTLIMITPERFRAME 50

struct D_D_KeyboardEvent {

    /* If keyDown is 1, a key has been
     *  pressed, 0 means it has been
     *  released. */
    int keyDown;

    /* This is D_Key, the int datatype makes
     *  sure it is 4 bytes.*/
    int key;
};

/* This struct is just for the purposes of making
 *  D_PumpEvents() work, even if it doesn't
 *  strictly store the state of input devices.
 *  This struct does store mouse state like x, y
 *  and buttons, but not keyboard state, instead
 *  it stores keyboard events, which can then be
 *  fired with D_CauseEvent().
 *
 * When a keydown or keyup event happens in JS,
 *  the JS variable D_KeyEventThisFrame gets
 *  incremented and the next item in
 *  keyboardEvent[] gets written to. On the next
 *  call to D_PumpEvents(), D_KeyEventThisFrame
 *  gets copied into
 *  inputState.keyEventsThisFrame and the events
 *  are fired with D_CauseEvent().
 *
 * This is essentially creating a second event
 *  queue for keyboard events. This is necessary
 *  to stop race conditions because the
 *  alternative is to call D_CauseEvent() when an
 *  event fires in the JS callback function, this
 *  could happen during a call to D_GetEvent().
 *
 * With this second event queue, keyboard events
 *  get stored in this struct and between calls
 *  to D_PumpEvents(). On the next call to
 *  D_PumpEvents(), the second event queue gets
 *  emptied and its events go into the drws-lib
 *  event queue.
 */
typedef struct D_D_InputState {
    int mouseX;
    int mouseY;
    int buttonState;
    int keyEventsThisFrame;
    struct D_D_KeyboardEvent keyboardEvent[D_D_KEYEVENTLIMITPERFRAME];
} D_D_InputState;


/* Front and back buffers to draw to. Limit the
 *  global state as much as possible, this global
 *  state is necessary because a D_Surf doesn't
 *  have a pointer to front buffer pixel data, it
 *  only has a pointer to back buffer pixel data
 *  (which is surf->pix).
 *
 * Note that there is some global state in JS
 *  with D_Canvas, etc. Search "window." with ctrl
 *  + f to find it.
 */
D_uint32 * D_D_Buffer1 = D_NULL;
D_uint32 * D_D_Buffer2 = D_NULL;


/* This finds the element with the id
 *  "drws-lib-canvas" and returns an outsurf that
 *  can be used to draw to it.
 *
 * If this function returns null, check the
 *  browser console log and make sure there is a
 *  <canvas> element on the page with an id of
 *  "drws-lib-canvas".
 *
 * It is unlikely but this function may also
 *  return null if (from within
 *  D_CreateSurfFrom()) D_CALLOC() fails and
 *  returns null, causing D_CreateSurfFrom() to
 *  return null, causing this function to return
 *  null.
 *
 * This function draws to buffers inside wasm
 *  memory, this means a buffer needs to be
 *  copied when calling D_FlipSurf(). This may
 *  need optimising in the future.
 *
 * x: This number gets ignored.
 * y: This number gets ignored.
 * w: The width to set the html canvas element to.
 * h: The height to set the html canvas element to.
 * title: This gets ignored.
 * flags: This gets ignored.
 * returns: A pointer to a surface or null on failure.
 */
D_Surf * D_GetOutSurf(int x, int y, int w, int h, char * title, D_OutSurfFlags flags){

    int foundUnusedCanvas = EM_ASM_INT({

        if(typeof D_Canvas !== 'undefined'){
            console.log("Drws-lib: Warning, D_GetOutSurf() called more than once without calling D_FreeOutSurf().");

            return 0;
        };

        window.D_Canvas = document.getElementById("drws-lib-canvas");

        if(!D_Canvas){
            console.log("Drws-lib: Warning, canvas element not found, make sure there is a <canvas> with an id of 'drws-lib-canvas'.");

            return 0;
        };

        if(D_Canvas.tagName != "CANVAS"){
            console.log("Drws-lib: Warning, element found with 'drws-lib-canvas' is not a <canvas> element.");

            return 0;
        };

        D_Canvas.width = $0;
        D_Canvas.height = $1;

        window.D_Context = D_Canvas.getContext('2d');
        window.D_ImageData = D_Context.getImageData(0, 0, D_Canvas.width, D_Canvas.height);
        //var data = imageData.data;

        return 1;
    }, w, h);

    if(!foundUnusedCanvas){
        return D_NULL;
    };

    if(D_D_Buffer1 == D_NULL){
        D_D_Buffer1 = D_CALLOC(w * h, sizeof(D_uint32));
    };

    if(D_D_Buffer2 == D_NULL){
        D_D_Buffer2 = D_CALLOC(w * h, sizeof(D_uint32));
    };

    D_Surf * surf = D_CreateSurfFrom(w, h, D_FindPixFormat(0xFF, 0xFF00, 0xFF0000, 0xFF000000, 32), D_D_Buffer1);

    surf->outId = 1;

    return surf;
};

/* This function frees a surf created by
 *  D_GetOutSurf().
 *
 * This function returns -1 if s is null and does
 *  nothing.
 *
 * If the surface passed in was not created by
 *  D_GetOutSurf(), the function returns -2 and
 *  does nothing.
 *
 * returns: 0 on success or a negative number on
 *  failure.
 */
int D_FreeOutSurf(D_Surf * s){

    if(s == D_NULL){
        return -1;
    };

    if(s->outId != 1){
        return -2;
    };

    s->outId = 0;

    D_FreeSurf(s);
    s = D_NULL;

    if(D_D_Buffer1 != D_NULL){
        D_FREE(D_D_Buffer1);
        D_D_Buffer1 = D_NULL;
    };

    if(D_D_Buffer2 != D_NULL){
        D_FREE(D_D_Buffer2);
        D_D_Buffer2 = D_NULL;
    };

    EM_ASM({
        D_ImageData = undefined;
        D_Context = undefined;
        D_Canvas = undefined;
    });

    return 0;
};

/* This function takes in a surface created by
 *  D_GetOutSurf() and shows it onscreen.
 *
 * To show the backbuffer onscreen, this function
 *  copies it onto a JS ImageData connected to
 *  the canvas. This may need optimising.
 *
 * If s is null, the function does nothing and
 *  returns -1.
 *
 * If s is has not been created by
 *  D_GetOutSurf(), the function does nothing and
 *  returns -2.
 *
 * s: The surface to show onscreen.
 * returns: 0 on success or a negative number on
 *  failure.
 */
int D_FlipOutSurf(D_Surf * s){
    if(s == D_NULL){
        return -1;
    };

    if(s->outId != 1){
        return -2;
    };

    EM_ASM({

        /* Apparently malloc in emscripen is
         *  always aligned to 8 bytes
         *  https://reviews.llvm.org/D104808 */

        var pixel = 0;

        for(var i = 0; i < (D_Canvas.width * D_Canvas.height); i++){
            pixel = getValue(($0) + (i * 4), "i32");

            D_ImageData.data[(i * 4)    ] = ((pixel       ) & 0xFF); //Red
            D_ImageData.data[(i * 4) + 1] = ((pixel >>>  8) & 0xFF); //Green
            D_ImageData.data[(i * 4) + 2] = ((pixel >>> 16) & 0xFF); //Blue
            D_ImageData.data[(i * 4) + 3] = ((pixel >>> 24) & 0xFF); //Alpha

        };

        D_Context.putImageData(D_ImageData, 0, 0);
    }, (int)(s->pix));

    /*Flip the front and back buffers.*/
    if(s->pix == D_D_Buffer1){
        s->pix = D_D_Buffer2;
    }else{
        s->pix = D_D_Buffer1;
    };

    return 0;
};

/* This is a small function to make it easier to
 *  use the ccall() function from JS. Using this
 *  function means only having to pass numbers
 *  instead of using D_CauseEvent() and having to
 *  pass a D_Event.
 */
#if 0
int D_D_SetMouseState(D_D_InputState * state, int x, int y, int button){
    state->mouseX = x;
    state->mouseY = y;


    /* Remember at this point that button is
     *  still in JS form. */

    /* Swap the middle click bit and right click
     *  bit. */
    if(button & 4){/*Middle button down?*/

        if(button & 2){/*Left button down?*/
            button = button | D_RIGHTBUTTON;
        }else{
            button = button & (~D_RIGHTBUTTON);
        };

        button = button | D_MIDDLEBUTTON;
    }else{

        if(button & 2){/*Left button down?*/
            button = button | D_RIGHTBUTTON;
        }else{
            button = button & (~D_RIGHTBUTTON);
        };

        button = button & (~D_MIDDLEBUTTON);
    };

    /* Now the button state should be in drws-lib
     *  form (D_MouseButton can be used, eg
     *  D_LEFTBUTTON, D_RIGHTBUTTON, etc) */


    state->buttonState = button;

    return 0;
};
#endif

/* This function pumps events into the event
 *  queue since the last call to D_PumpEvents().
 *
 * This function uses the setValue() function
 *  from preamble.js.
 *
 * This function allocates two D_D_InputState
 *  structures without freeing them, it does this
 *  once the first time it gets called. If
 *  D_CALLOC() fails, this function does nothing
 *  and returns -1.
 *
 * returns: 0 on success or a negative number on
 *  fail.
 */
int D_PumpEvents(){


    static D_D_InputState * inputState = D_NULL;

    /*Old state from last call to D_PumpEvents()*/
    static D_D_InputState * oldInputState = D_NULL;

     if(inputState == D_NULL){
         inputState = D_CALLOC(1, sizeof(D_D_InputState));
     };

     if(oldInputState == D_NULL){
         oldInputState = D_CALLOC(1, sizeof(D_D_InputState));
     };

     /* In case D_CALLOC didn't work. */
     if(inputState == D_NULL || oldInputState == D_NULL){
         return -1;
     };


     /* Keep the input state from the last call to
      *  D_PumpEvents() in oldInputState. */
     oldInputState->mouseX = inputState->mouseX;
     oldInputState->mouseY = inputState->mouseY;
     oldInputState->buttonState = inputState->buttonState;


    /* Cause inputState to be updated when events
     *  fire in JS.*/
    EM_ASM({

        /* Some useful links:
         * https://developer.mozilla.org/en-US/docs/Web/API/Event
         * https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
         * https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
         *
         * https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event
         */

        if(typeof D_MouseX === 'undefined'){window.D_MouseX = 0};
        if(typeof D_MouseY === 'undefined'){window.D_MouseY = 0};
        if(typeof D_ButtonState === 'undefined'){window.D_ButtonState = 0};
        if(typeof D_LastElementClicked === 'undefined'){window.D_LastElementClicked = document.querySelector("body")};
        if(typeof D_KeyEventsThisFrame === 'undefined'){window.D_KeyEventsThisFrame = 0;};

        /* Note that mouse state is in JS
         *  form with 2 being right click,
         *  not drws-lib form with 2 being
         *  middle click.*/

        /*Setup callback function in JS */
        if(typeof D_EventCallback === 'undefined'){

            window.D_EventCallback = function(event) {
                switch(event.type){
                    case "mousemove":
                    case "mousedown":
                    case "mouseup":

                        D_MouseX = event.clientX;
                        D_MouseY = event.clientY;
                        D_ButtonState = event.buttons;

                        //ccall('D_D_SetMouseState', 'number', ['number', 'number', 'number', 'number'], [$0, event.clientX, event.clientY, event.buttons]);

                        break;
                };
            };

            D_Canvas.addEventListener("mousemove", D_EventCallback);
            D_Canvas.addEventListener("mousedown", D_EventCallback);
            D_Canvas.addEventListener("mouseup", D_EventCallback);
        };

        /* Setup keyboard callback function */
        if(typeof D_BodyEventCallback === 'undefined'){
            window.D_BodyEventCallback = function(event) {
                switch(event.type){
                    case "keydown":

                        if(D_Canvas === D_LastElementClicked){
                            /*console.log("keydown on canvas! " + event.key);*/

                            /* Write 1 to
                             *  inputState->keyboardEvent[D_KeyEventsThisFrame].keydown*/
                            setValue(($0 + 16) + (D_KeyEventsThisFrame * 8), 1, "i32");

                        }else{
                            /*console.log("kedown off canvas! " + event.key);*/
                        };

                        break;

                    case "keyup":

                        if(D_Canvas === D_LastElementClicked){
                            /*console.log("keyup on canvas! " + event.key);*/

                            /* Write 0 to
                             *  inputState->keyboardEvent[D_KeyEventsThisFrame].keydown*/
                            setValue(($0 + 16) + (D_KeyEventsThisFrame * 8), 0, "i32");

                        }else{
                            /*console.log("keyup off canvas! " + event.key);*/
                        };

                        break;

                    case "mouseup":
                        D_LastElementClicked = event.target;
                        break;
                };

                if(event.type === "keydown" || event.type === "keyup"){

                    /* Write 0 to
                     *  inputState->keyboardEvent[D_KeyEventsThisFrame].key*/
                    setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 0, "i32");

                    /*console.log("key " + event.key);*/

                    /* The below switch writes a
                     *  D_Key to
                     *  inputState->keyboardEvent[D_KeyEventsThisFrame].key
                     *
                     * If D_Key in devents.h
                     *  changes, this switch
                     *  would also have to
                     *  change.
                     */

                    switch(event.key){
                        case "A": case "a": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  1, "i32"); break;
                        case "B": case "b": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  2, "i32"); break;
                        case "C": case "c": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  3, "i32"); break;
                        case "D": case "d": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  4, "i32"); break;
                        case "E": case "e": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  5, "i32"); break;
                        case "F": case "f": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  6, "i32"); break;
                        case "G": case "g": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  7, "i32"); break;
                        case "H": case "h": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  8, "i32"); break;
                        case "I": case "i": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  9, "i32"); break;
                        case "J": case "j": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 10, "i32"); break;
                        case "K": case "k": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 11, "i32"); break;
                        case "L": case "l": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 12, "i32"); break;
                        case "M": case "m": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 13, "i32"); break;
                        case "N": case "n": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 14, "i32"); break;
                        case "O": case "o": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 15, "i32"); break;
                        case "P": case "p": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 16, "i32"); break;
                        case "Q": case "q": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 17, "i32"); break;
                        case "R": case "r": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 18, "i32"); break;
                        case "S": case "s": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 19, "i32"); break;
                        case "T": case "t": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 20, "i32"); break;
                        case "U": case "u": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 21, "i32"); break;
                        case "V": case "v": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 22, "i32"); break;
                        case "W": case "w": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 23, "i32"); break;
                        case "X": case "x": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 24, "i32"); break;
                        case "Y": case "y": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 25, "i32"); break;
                        case "Z": case "z": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 26, "i32"); break;

                        case "0": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  27, "i32"); break;
                        case "1": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  28, "i32"); break;
                        case "2": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  29, "i32"); break;
                        case "3": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  30, "i32"); break;
                        case "4": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  31, "i32"); break;
                        case "5": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  32, "i32"); break;
                        case "6": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  33, "i32"); break;
                        case "7": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  34, "i32"); break;
                        case "8": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  35, "i32"); break;
                        case "9": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  36, "i32"); break;

                        case "!": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  37, "i32"); break;
                        case '"': setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  38, "i32"); break;
                        case "£": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  39, "i32"); break;
                        case "$": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  40, "i32"); break;
                        case "%": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  41, "i32"); break;
                        case "^": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  42, "i32"); break;
                        case "&": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  43, "i32"); break;
                        case "*": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  44, "i32"); break;
                        case "(": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  45, "i32"); break;
                        case ")": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4,  46, "i32"); break;

                        case "Left":  case "ArrowLeft":  setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 47, "i32"); break;
                        case "Right": case "ArrowRight": setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 48, "i32"); break;
                        case "Up":    case "ArrowUp":    setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 49, "i32"); break;
                        case "Down":  case "ArrowDown":  setValue(($0 + 16) + (D_KeyEventsThisFrame * 8) + 4, 50, "i32"); break;
                    };

                    D_KeyEventsThisFrame++;

                };
            };

            document.querySelector("body").addEventListener("keydown", D_BodyEventCallback);
            document.querySelector("body").addEventListener("keyup", D_BodyEventCallback);
            document.querySelector("body").addEventListener("mouseup", D_BodyEventCallback);
        };

        /* Update inputState from JS */
        setValue($0 + 0, D_MouseX, "i32");
        setValue($0 + 4, D_MouseY, "i32");
        setValue($0 + 8, D_ButtonState, "i32");


        /* Write to
         *  inputState->keyEventsThisFrame */
        setValue(($0 + 12), D_KeyEventsThisFrame, "i32");

        /* Reset to 0 each call to
         *  D_PumpEvents(). */
        D_KeyEventsThisFrame = 0;

    }, ((int)(inputState)) );

    /*EM_ASM({console.log("keyEvents: " + $0 + " [keyDown " + $1 + " key " + $2 + "] [keyDown " + $3 + " key " + $4 + "]")}, inputState->keyEventsThisFrame, inputState->keyboardEvent[0].keyDown, inputState->keyboardEvent[0].key, inputState->keyboardEvent[1].keyDown, inputState->keyboardEvent[1].key);*/


    /* Remember at this point that button is
     *  still in JS form. */

    /* Swap the middle click bit and right click
     *  bit. */
    if(inputState->buttonState & 4){/*Middle button down?*/

        if(inputState->buttonState & 2){/*Left button down?*/
            inputState->buttonState = inputState->buttonState | D_RIGHTBUTTON;
        }else{
            inputState->buttonState = inputState->buttonState & (~D_RIGHTBUTTON);
        };

        inputState->buttonState = inputState->buttonState | D_MIDDLEBUTTON;
    }else{

        if(inputState->buttonState & 2){/*Left button down?*/
            inputState->buttonState = inputState->buttonState | D_RIGHTBUTTON;
        }else{
            inputState->buttonState = inputState->buttonState & (~D_RIGHTBUTTON);
        };

        inputState->buttonState = inputState->buttonState & (~D_MIDDLEBUTTON);
    };

    /* Now the button state should be in drws-lib
     *  form (D_MouseButton can be used, eg
     *  D_LEFTBUTTON, D_RIGHTBUTTON, etc) */


    /*EM_ASM({console.log("Pump x " + $0 + " y " + $1 + " button " + $2)}, inputState->mouseX, inputState->mouseY, inputState->buttonState);*/


    D_Event e = {0};


    /* Fire drws-lib events based on the new
     * input state. */

    /* Has the the mouse gone down? */
    if(oldInputState->buttonState == 0 &&
       inputState->buttonState != 0){

        /* Fire a mouse down event. */
        e.type = D_MOUSEDOWN;
        e.mouse.x = inputState->mouseX;
        e.mouse.y = inputState->mouseY;
        e.mouse.button = inputState->buttonState;
        D_CauseEvent(&e);


    /* Has the mouse gone up? */
    }else if(oldInputState->buttonState != 0 &&
             inputState->buttonState == 0){

        /* Fire a mouse up event. */
        e.type = D_MOUSEUP;
        e.mouse.x = inputState->mouseX;
        e.mouse.y = inputState->mouseY;
        e.mouse.button = inputState->buttonState;
        D_CauseEvent(&e);


    /* Has the mouse moved? */
    }else if(inputState->mouseX != oldInputState->mouseX ||
             inputState->mouseY != oldInputState->mouseY){

        /* Fire a mouse move event. */
        e.type = D_MOUSEMOVE;
        e.mouse.x = inputState->mouseX;
        e.mouse.y = inputState->mouseY;
        e.mouse.button = inputState->buttonState;
        D_CauseEvent(&e);
    };

    {
        int i = 0;
        while(i < inputState->keyEventsThisFrame){

            if(inputState->keyboardEvent[i].keyDown == 1){
                e.type = D_KEYDOWN;
            }else{
                e.type = D_KEYUP;
            };

            e.keyboard.key = inputState->keyboardEvent[i].key;

            /* Only case the event if the key is
             *  a valid D_Key. */
            if(e.keyboard.key > 0 && e.keyboard.key < D_NumKeys){
                D_CauseEvent(&e);
            };

            i++;
        };
    }


    return 0;
};
